### ISSUE TITLE
Mematikan fungsi anti_bounce 

### ISSUE THREAD

**Issue by radenvodka** [radenvodka/Sendinbox-#10]
Buka file smtp-config.php lalu 

> 'anti_bounce' 			=> true,  rubahlah true menjadi false

**Comment by DanisGans** [comment]
Aku cari nda ada di  smtp-config.php ndak ada anti_bounce mas 
aku racik bounce terus ini mas

**Comment by ekasyahwan** [comment]
Untuk menikmati settingan anti_bounce kamu harus punya sendinbox versi pro

**Comment by DanisGans** [comment]
mau2

**Comment by ekasyahwan** [comment]
Bisa langsung beli di http://bmarket.or.id

**Comment by BayKoala48** [comment]
Jdi Fitur ini ndk bisa dipakai apa mass ?

**Comment by ekasyahwan** [comment]
bisa

**Comment by ridho88** [comment]
kalau anti bounce dimatikan mending beli yg biasa
tertarik sm pro karna anti bouncenya aja sih

**Comment by ekasyahwan** [comment]
kekuranganya yang rev itu banyak mas bisa cek di https://github.com/ekasyahwan/Sendinbox-
