### ISSUE TITLE
Encryp kata 

### ISSUE THREAD

**Issue by rebert17** [radenvodka/Sendinbox-#11]
Mohon bantuan nya bang ,d bagian encryp kata pada smtp-config.php  , itu di isi apa ya

**Comment by ekasyahwan** [comment]
Misal kamu memiliki letter dengan kata-kata : 

> Selamat datang di sendinbox 

kamu pengen encrypt kata selamat , datang , sendinbox maka isikan kata" di atas di 

'encrypt_kata' 			=> array('selamat','datang','sendinbox'),
