### ISSUE TITLE
Penyebab emails Anda mengalami bounce (wajib baca bila kamu mengaktifkan di sendinbox)

### ISSUE THREAD

**Issue by radenvodka** [radenvodka/Sendinbox-#12]
1. Alamat email tidak ada
2. Email tidak bisa terkirim
3. Mailbox Penuh
4. Balasan Berlibur/Otomatis
5. Email terblokir

di sendinbox sendiri sudah memiliki fitur anti bounce , namun untuk host seperti hotmail , yahoo , aol itu memiliki batasan per-ip. 

sistem sendinbox anti bounce : 
Sendinbox akan mengirimkan request ke host email dan mengecek apakah email penerima terdaftar atau tidak. jika iya maka akan di send namun jika di blockir maka sendinbox tidak akan mengirim email tsbt.

**Comment by BayKoala48** [comment]
brarti fitur anti bounce tetep bisa di pakek dan hemat limit relay ini ya mas

**Comment by ekasyahwan** [comment]
iya mas

**Comment by ekasyahwan** [comment]
namun kelemahanya mereka para email baru itu di anggap tidak terdaftar
