### ISSUE TITLE
Kesalahan SMTP: Tidak dapat mengautentikasi

### ISSUE THREAD

**Issue by radenvodka** [radenvodka/Sendinbox-#16]
> Mau tanyak Ini masalah kenapa ya
> udah ganti smtp semua gini
> jadi setiap nebar 5k
> kadang 400 - 600 sukses
> sisanya gini kenaao ya ? oleh Ariel Septian‎ 

di jawab oleh Anton Putra 

> Ada beberapa account reley user yg di kasik 600 email per send
> Tapi klo kita creat ulang user baru bakal jalan lagi

**Comment by k1ngsabun** [comment]
belum di buat send aja udh tidak dapat mengautentikasi gimana tuh? 
padahal kalau di send manual via gmail bisa . tp pas pake sendinbox tidak dapat mengautentikasi

**Comment by rahmann0ob** [comment]
aku kemarin gitu , terus send lewat vps lancar mas.
