### ISSUE TITLE
SMTP Error: Could not authenticate

### ISSUE THREAD

**Issue by radenvodka** [radenvodka/Sendinbox-#28]
1.  Pastikan username dan password smtp benar.
2. Pastikan port dan secure di setting dengan benar.

ada saran jika masih error bisa setting smtp kalian 
![36521872-db9c658c-17cb-11e8-95f8-29ba6d0c6c54](https://user-images.githubusercontent.com/5636480/36920768-64c91cf0-1e94-11e8-9a2d-7ada6e2a484e.png)

problem ini solved di issue phpmailer : https://github.com/PHPMailer/PHPMailer/issues/1362

**Comment by ekasyahwan** [comment]
ada lagi  , silahkan izinkan email kamu untuk di pakai pihak ke 3 : https://myaccount.google.com/lesssecureapps
