### ISSUE TITLE
Cara memudahkan INBOX

### ISSUE THREAD

**Issue by radenvodka** [radenvodka/Sendinbox-#5]
ada banyak faktor 

1. IP , silahkan cek IP kalian apakah banyak BL nya ? bisa cek di whatismyipaddress.com/blacklist-check
2. Subject , silahkan riset dibagian subject , gunakan random subject biar inbox 
3. Letter
4. From Name / Email , ini juga berpengaruh
5. Bermain dengan Custom header.

**Comment by ekasyahwan** [comment]
ndak perasaan ku
